export const defaultSeedData = {
  services: [
    {
      serviceNumber: '01',
      title: 'Creative Reel / Ad',
      tagline: 'Turn attention into action.',
      description:
        'High-impact reels and video advertisements designed to make your brand stand out, connect with your audience and drive action.',
      tags: [
        'Promotional Reels',
        'Product Videos',
        'Business Videos',
        'Short-form Ads',
        'Campaign Videos',
      ],
      icon: 'Video',
      active: true,
      order: 1,
    },
    {
      serviceNumber: '02',
      title: 'UGC & AI Video Ads',
      tagline: 'Authentic content. Smarter production.',
      description:
        'UGC-style and AI-powered video ads designed to make your brand feel relatable, modern and memorable.',
      tags: [
        'UGC Creator Ads',
        'AI Voice & Visuals',
        'Hook Testing',
        'Rapid Iteration',
        'TikTok & IG Ads',
      ],
      icon: 'Sparkles',
      active: true,
      order: 2,
    },
    {
      serviceNumber: '03',
      title: 'Creative Graphics',
      tagline: 'Make your brand impossible to ignore.',
      description:
        'Scroll-stopping social media creatives, promotional designs and visual content built to make your brand look professional and premium.',
      tags: [
        'Social Creatives',
        'Posters & Banners',
        'Thumbnails',
        'Brand Identity',
        'Marketing Assets',
      ],
      icon: 'Palette',
      active: true,
      order: 3,
    },
    {
      serviceNumber: '04',
      title: 'Meta Ads',
      tagline: 'Reach the right people. Drive real results.',
      description:
        'Strategic advertising campaigns designed to reach your ideal audience and turn attention into business opportunities.',
      tags: [
        'Lead Generation',
        'Local Awareness',
        'WhatsApp Leads',
        'Sales Campaigns',
        'ROAS Optimization',
      ],
      icon: 'Target',
      active: true,
      order: 4,
    },
    {
      serviceNumber: '05',
      title: 'Social Media Management',
      tagline: 'Your brand. Always active. Always growing.',
      description:
        'Consistent content, creative planning and professional social media management to build a stronger presence across social platforms.',
      tags: [
        'Content Planning',
        'Community Management',
        'Content Scheduling',
        'Growth Strategy',
        'Performance Monitoring',
      ],
      icon: 'Share2',
      active: true,
      order: 5,
    },
    {
      serviceNumber: '06',
      title: 'Website Development',
      tagline: 'Build your digital home.',
      description:
        'Modern, responsive and mobile-friendly websites designed to strengthen your online presence and help your business look more professional online.',
      tags: [
        'Custom Web Design',
        'High Conversion Landing Pages',
        'Mobile-First Experience',
        'Speed & SEO Ready',
        'CMS Integration',
      ],
      icon: 'Globe',
      active: true,
      order: 6,
    },
  ],
  projects: [
    {
      title: 'LuxeAura High-Conversion E-Commerce Scaling',
      slug: 'luxeaura-ecommerce-scaling',
      client: 'LuxeAura Skincare',
      category: 'Creative Ads & Meta Campaigns',
      shortDescription:
        'Engineered a multi-hook UGC reel campaign and optimized Meta Ads funnel driving 4.8x ROAS.',
      description:
        'LuxeAura needed to break through market saturation in the premium skincare category. ScaleUp Media designed a comprehensive creative sprint producing 24 high-converting short-form video hooks, deployed with algorithmic Meta Ads scaling, leading to exponential revenue growth within 90 days.',
      thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1200&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1200&auto=format&fit=crop',
      ],
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      externalUrl: 'https://scaleupmedia.io',
      results: '+380% Qualified Revenue Growth | 4.8x Meta Ads ROAS | 2.4M Video Views',
      featured: true,
      active: true,
      order: 1,
    },
    {
      title: 'Nova AI SaaS Platform Launch & Growth Strategy',
      slug: 'nova-ai-saas-launch',
      client: 'Nova AI Technologies',
      category: 'Brand Identity & Web Development',
      shortDescription:
        'Full brand design system, interactive 3D web experience, and targeted B2B lead generation.',
      description:
        'For Nova AI, we built a conversion-focused web identity and executed high-intent B2B social campaigns that delivered thousands of waitlist signups and enterprise demo requests.',
      thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
      ],
      externalUrl: 'https://scaleupmedia.io',
      results: '14,200+ Demo Signups | 42% Landing Page Conversion | #1 Product Hunt Launch',
      featured: true,
      active: true,
      order: 2,
    },
    {
      title: 'Apex Timepieces Viral Organic & Paid Domination',
      slug: 'apex-timepieces-viral-campaign',
      client: 'Apex Horology',
      category: 'Creative Reels & Social Management',
      shortDescription:
        'Hyper-polished 4K cinematic reels and consistent community management resulting in viral brand awareness.',
      description:
        'We created cinematic product reels focusing on macro mechanics and lifestyle prestige. Combined with proactive community management, Apex grew its Instagram following by 180k organic engaged members.',
      thumbnail: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1200&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1200&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1200&auto=format&fit=crop',
      ],
      results: '180K+ Organic Followers | 8.9M Organic Reach | $1.2M Direct Attributed Sales',
      featured: true,
      active: true,
      order: 3,
    },
    {
      title: 'Horizon Capital WhatsApp Lead Engine',
      slug: 'horizon-capital-whatsapp-funnel',
      client: 'Horizon Wealth',
      category: 'Meta Ads & WhatsApp Automation',
      shortDescription:
        'Direct-to-WhatsApp high-ticket consultation funnel delivering 350+ verified high-net-worth investor calls.',
      description:
        'Designed high-trust Meta ad creatives with seamless one-click WhatsApp redirection, reducing acquisition costs by 54% compared to standard landing page funnels.',
      thumbnail: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop',
      gallery: [
        'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop',
      ],
      results: '-54% Cost Per Lead | 350+ Qualified HNI Consultations | $4.2M Asset Pipeline',
      featured: true,
      active: true,
      order: 4,
    },
  ],
  testimonials: [
    {
      clientName: 'Aarav Sharma',
      company: 'Founder, LuxeAura',
      review:
        'ScaleUp Media transformed our digital presence. Their creative reels completely changed our conversion rates, delivering an incredible 4.8x ROAS within just 60 days.',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 1,
      active: true,
      order: 1,
    },
    {
      clientName: 'Rohan Mehta',
      company: 'CMO, Nova Technologies',
      review:
        'The team understands digital growth like few agencies do. Strategy, design, and performance are all executed at an elite level. Highly recommended!',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 1,
      active: true,
      order: 2,
    },
    {
      clientName: 'Elena Rostova',
      company: 'Brand Director, Apex Horology',
      review:
        'Our engagement shot up 300% after ScaleUp took over our reels and creative graphics. Their visual polish is truly world-class.',
      profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 1,
      active: true,
      order: 3,
    },
    {
      clientName: 'Vikramaditya Singhania',
      company: 'Managing Director, Horizon Capital',
      review:
        'The WhatsApp lead generation engine ScaleUp built for us scaled our client acquisition effortlessly. Direct, transparent, and high-impact.',
      profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 2,
      active: true,
      order: 4,
    },
    {
      clientName: 'Priya Verma',
      company: 'Co-Founder, Velvet Skin Studio',
      review:
        'Their UGC and AI video ads performed 3x better than our previous agency creatives. They deliver on every single promise with clockwork precision.',
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 2,
      active: true,
      order: 5,
    },
    {
      clientName: 'Sameer Kulkarni',
      company: 'CEO, Kinetic Fitness Labs',
      review:
        'From high-impact video ads to full website development, ScaleUp Media elevated our brand from unknown to industry benchmark.',
      profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=300&auto=format&fit=crop',
      rating: 5,
      marqueeRow: 2,
      active: true,
      order: 6,
    },
  ],
  sectionSettings: {
    hero: true,
    reality: true,
    services: true,
    whyScaleUp: true,
    projects: true,
    testimonials: true,
    process: true,
    promise: true,
    cta: true,
    footer: true,
    floatingWhatsApp: true,
  },
  contactSettings: {
    phone: '6268523635',
    whatsAppNumber: '6268523635',
    defaultWhatsAppMessage:
      "Hi ScaleUp Media, I'm interested in scaling my brand with your growth & creative services. Let's talk!",
    email: 'shivamconnect65@gmail.com',
    instagram: '@scaleup.media.io',
    founderInstagram: '@shivamxbizz',
    facebook: 'https://facebook.com/scaleupmedia',
    linkedin: 'https://linkedin.com/company/scaleupmedia',
    youtube: 'https://youtube.com/@scaleupmedia',
    address: 'Mumbai & Global Operations, India',
    founderName: 'Shivam',
    founderBio:
      'Building brands through smart business strategy, creative marketing and high-impact content. From shooting and editing to paid advertising, we turn ideas into digital growth.',
    founderPhotoUrl: '',
    founderPhotoFileId: '',
    founderLinkedin: '',
    founderFacebook: '',
    founderYoutube: '',
  },
  websiteContent: {
    heroHeading: 'WE BUILD BRANDS THAT GET NOTICED.',
    heroDescription:
      'Strategy, creative content and performance marketing designed to help businesses grow.',
    heroPrimaryBtn: 'Start a Project →',
    heroSecondaryBtn: 'View Our Work →',
    realityHeading: 'YOUR CUSTOMERS ARE ALREADY ONLINE.',
    realityDescription:
      'They are discovering businesses on Instagram, comparing brands, searching online and deciding who to trust.',
    realityPoints: [
      {
        title: 'Low online visibility',
        desc: 'Lost in the digital noise without a strategic positioning footprint.',
      },
      {
        title: 'Inconsistent content',
        desc: 'Irregular posting schedule eroding brand credibility and algorithm favor.',
      },
      {
        title: 'Weak digital presence',
        desc: 'Unoptimized touchpoints failing to build trust with modern buyers.',
      },
      {
        title: 'Poor branding',
        desc: 'Outdated visuals failing to command premium pricing or brand authority.',
      },
      {
        title: 'Competitors getting more attention',
        desc: 'Rivals seizing market share through aggressive creative execution.',
      },
    ],
    realityStatement: 'IF YOUR BUSINESS IS NOT VISIBLE, SOMEONE ELSE WILL BE.',
    whyScaleUpHeading: 'NOT JUST MARKETING. WE BUILD DIGITAL GROWTH.',
    whyScaleUpSubtitle:
      'A disciplined, data-informed creative system designed to turn passive scrollers into long-term brand advocates.',
    whyScaleUpItems: [
      { number: '01', title: 'Strategy', desc: 'Know what to do.' },
      { number: '02', title: 'Content', desc: 'Get attention.' },
      { number: '03', title: 'Creative', desc: 'Build a memorable brand.' },
      { number: '04', title: 'Advertising', desc: 'Reach the right people.' },
      { number: '05', title: 'Execution', desc: 'Turn ideas into action.' },
    ],
    promiseLabel: 'THE SCALEUP PROMISE',
    promiseHeading: 'YOUR GROWTH IS THE GOAL.',
    promiseText1: "We don't believe in random posting.",
    promiseText2: "We don't believe in vanity metrics.",
    promiseStatement: 'We believe in strategy, creativity and consistent execution.',
    promiseWords: ['ATTENTION.', 'TRUST.', 'GROWTH.'],
    ctaHeading: 'READY TO SCALE YOUR BRAND?',
    ctaDescription:
      "Let's turn your digital presence into something people remember.",
    ctaButtonText: 'START YOUR GROWTH JOURNEY →',
    footerTagline: 'GROWTH. STRATEGY. IMPACT.',
  },
  branding: {
    brandName: 'ScaleUp Media',
    tagline: 'GROWTH. STRATEGY. IMPACT.',
    logoUrl: '',
    logoFileId: '',
    faviconUrl: '',
    faviconFileId: '',
  },
  themeSettings: {
    preset: 'scaleup-navy',
    backgroundColor: '#07111F',
    surfaceColor: '#0D1B2A',
    surfaceSecondaryColor: '#10253A',
    primaryColor: '#2563EB',
    accentColor: '#08BDF5',
    accentSecondaryColor: '#08BDF5',
    textColor: '#FFFFFF',
    secondaryTextColor: '#AAB8C8',
    borderColor: 'rgba(255,255,255,0.10)',
    customizationEnabled: false,
  },
};

